const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const API="api.php";
let state=JSON.parse(localStorage.getItem("edunexaV4")||'{"guestProgress":0,"solved":0,"correct":0,"streak":0,"lastDay":null,"notes":[],"notifications":[{"title":"Welcome to EduNexa V4","body":"Explore the complete study library.","time":"Now"},{"title":"Daily challenge","body":"New randomized questions are ready.","time":"Today"},{"title":"Study reminder","body":"A focused 25-minute session can keep your streak alive.","time":"Today"}]}');
let currentUser=null,authMode="login",quiz=[],qIndex=0,qScore=0,timer=1500,timerInt=null;

function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function saveState(){localStorage.setItem("edunexaV4",JSON.stringify(state))}
function page(id){$$(".page").forEach(x=>x.classList.remove("active"));$("#"+id)?.classList.add("active");$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===id));window.scrollTo({top:0,behavior:"smooth"});if(innerWidth<801)$("#sidebar").classList.remove("open")}
document.addEventListener("click",e=>{const b=e.target.closest("[data-page]");if(b){const id=b.dataset.page;if(id==="chapter")page("chapter");else page(id)}});

$("#mobileMenu").onclick=()=>$("#sidebar").classList.add("open");$("#sideClose").onclick=()=>$("#sidebar").classList.remove("open");
$("#theme").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light")};
if(localStorage.getItem("theme")==="dark")document.body.classList.add("dark");

function touchFx(){document.querySelectorAll("button,.subject,.exam,.feature-grid button").forEach(x=>x.addEventListener("touchstart",()=>x.classList.add("touching"),{passive:true}))}
function renderStats(){let solved=currentUser?.solved??state.solved;let correct=currentUser?.correct??state.correct;let streak=currentUser?.streak??state.streak;let progress=solved?Math.round(correct/solved*100):0;$("#homeStats").innerHTML=[["📚",CURRICULUM.length,"Subjects"],["📖",CURRICULUM.reduce((a,s)=>a+s.chapters.length,0)+"+","Chapters"],["🧠",solved,"MCQs solved"],["🔥",streak+"","Day streak"]].map(x=>`<div class="stat"><span class="ico">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join("");$("#sideStreak").textContent=streak}
function renderContinue(){let arr=CURRICULUM.slice(0,4);$("#continue").innerHTML=arr.map((s,i)=>{let p=currentUser?Math.min(100,Math.round((currentUser.progress?.[s.subject]||[22,46,68,34][i]))):[22,46,68,34][i];return `<div class="learn-row"><span class="iconbox">${["⚛️","🧪","📐","🧬"][i]}</span><div><b>${s.subject}</b><small>${s.chapters[Math.min(i,s.chapters.length-1)].name}</small></div><strong>${p}%</strong></div>`}).join("")}
function renderGoals(){let p=Math.min(30,currentUser?.solved||state.solved);$("#goals").innerHTML=[["📖","Complete 2 chapters",p?1:0,"2"],["🧠","Solve 30 MCQs",p,"30"],["⏱️","Study for 60 minutes",p?45:0,"60"]].map((g,i)=>`<div class="goal"><div class="goal-top"><span>${g[0]} ${g[1]}</span><span>${g[2]}/${g[3]}</span></div><div class="bar"><i style="width:${Math.min(100,g[2]/g[3]*100)}%"></i></div></div>`).join("")}
function renderPerformance(){let data=CURRICULUM.slice(0,5).map((s,i)=>[s.subject,[0,0,0,0,0][i]]);if(currentUser?.performance)data=data.map(([n],i)=>[n,currentUser.performance[n]||0]);$("#homePerformance").innerHTML=data.map(([n,p])=>`<div class="goal"><div class="goal-top"><span>${n}</span><span>${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`).join("")}
function populateSelects(){let ss=CURRICULUM.map(s=>s.subject);$("#subjectSelect").innerHTML='<option value="all">All subjects</option>'+ss.map(s=>`<option>${s}</option>`).join("");$("#quizSubject").innerHTML='<option>All Subjects</option>'+ss.map(s=>`<option>${s}</option>`).join("")}
function renderLibrary(){let q=($("#librarySearch").value||"").toLowerCase(),filter=$("#subjectSelect").value;let html="";CURRICULUM.filter(s=>filter==="all"||s.subject===filter).forEach(s=>{let chapters=s.chapters.filter(c=>(s.subject+" "+c.name+" "+c.topics.map(t=>t.name+" "+t.definition).join(" ")).toLowerCase().includes(q));if(!chapters.length)return;html+=`<article class="subject"><div class="subject-head"><span class="subject-icon">${{"Physics":"⚛️","Chemistry":"🧪","Mathematics":"📐","Biology":"🧬","English":"📚","Computer":"💻"}[s.subject]||"📘"}</span><div><h3>${s.subject}</h3><small>${chapters.length} matching chapters • ${s.chapters.reduce((a,c)=>a+c.topics.length,0)} topics</small></div></div>${chapters.map((c,ci)=>`<div class="chapter-row"><span>${ci+1}. ${escapeHTML(c.name)}</span><button data-chapter="${escapeHTML(s.subject)}|${escapeHTML(c.name)}">Study →</button></div>`).join("")}</article>`});$("#libraryGrid").innerHTML=html||'<div class="card"><h2>No matching topic</h2><p class="muted">Try another chapter, subject or keyword.</p></div>';$$("[data-chapter]").forEach(b=>b.onclick=()=>openChapter(...b.dataset.chapter.split("|")))}
function openChapter(subject,chapter){let s=CURRICULUM.find(x=>x.subject===subject),c=s?.chapters.find(x=>x.name===chapter);if(!c)return;$("#chapterContent").innerHTML=`<div class="page-title"><p class="eyebrow">${escapeHTML(subject)}</p><h1>${escapeHTML(c.name)}</h1><p>${c.topics.length} topic notes • definitions • key points</p></div>${c.topics.map(t=>`<article class="topic"><div class="topic-head"><b>${escapeHTML(t.name)}</b><span>＋</span></div><div class="topic-body"><p><span class="note-label">Definition:</span> ${escapeHTML(t.definition)}</p><p><span class="note-label">Study notes:</span> ${escapeHTML(t.notes)}</p><p><span class="note-label">Revision:</span> Learn the definition, understand the concept, solve at least 5 related questions, then revisit it during revision.</p></div></article>`).join("")}`;$$(".topic-head").forEach(x=>x.onclick=()=>x.parentElement.classList.toggle("open"));page("chapter")}
function renderEntrance(id,subjects){$("#"+id+"Cards").innerHTML=subjects.map((n,i)=>`<div class="mini"><b>${["📘","🧪","📐","🧬","🧠"][i%5]} ${n}</b><small>${CURRICULUM.find(s=>s.subject===n)?.chapters.length||8} chapters • Practice available</small></div>`).join("")}
function syncUI(){renderStats();renderContinue();renderGoals();renderPerformance();$("#authBtn").hidden=!!currentUser;$("#userMini").hidden=!currentUser;if(currentUser){$("#userName").textContent=currentUser.name;$("#userAvatar").textContent=currentUser.name[0].toUpperCase();$("#analyticsHint").textContent="Your profile statistics are linked to your account."}else $("#analyticsHint").textContent="Sign in to save analytics across sessions and devices."}
function renderAnalytics(){let solved=currentUser?.solved??state.solved,correct=currentUser?.correct??state.correct,streak=currentUser?.streak??state.streak,acc=solved?Math.round(correct/solved*100):0;$("#analyticsContent").innerHTML=`<div class="profile-card"><div class="metric"><b>${solved}</b><small>Questions solved</small></div><div class="metric"><b>${acc}%</b><small>Accuracy</small></div><div class="metric"><b>${streak}</b><small>Day streak</small></div><div class="metric"><b>${currentUser?.studyMinutes||0}m</b><small>Study time</small></div></div><div class="card" style="margin-top:15px"><h2>Subject performance</h2>${CURRICULUM.slice(0,6).map(s=>{let p=currentUser?.performance?.[s.subject]||0;return `<div class="goal"><div class="goal-top"><span>${s.subject}</span><span>${p}%</span></div><div class="bar"><i style="width:${p}%"></i></div></div>`}).join("")}</div>`}

function dailyStreak(){let today=new Date().toISOString().slice(0,10);if(!state.lastDay){state.lastDay=today;state.streak=1;saveState()}else if(state.lastDay!==today){let prev=new Date(state.lastDay),now=new Date(today);let days=Math.round((now-prev)/86400000);state.streak=days===1?state.streak+1:1;state.lastDay=today;saveState()}}
dailyStreak();

async function api(action,data={}){try{let r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...data})});return await r.json()}catch(e){return {ok:false,error:"Backend unavailable. The front-end guest mode is still working."}}}

function openAuth(mode="login"){authMode=mode;$("#authModal").classList.add("open");renderAuth()}
function renderAuth(){ $$(".auth-tab").forEach(x=>x.classList.toggle("active",x.dataset.auth===authMode));$("#authFields").innerHTML=authMode==="signup"?`<input name="name" required placeholder="Full name"><input name="email" type="email" required placeholder="Email"><input name="password" type="password" minlength="6" required placeholder="Password (min 6 characters)">`:`<input name="email" type="email" required placeholder="Email"><input name="password" type="password" required placeholder="Password">`;$("#authSubmit").textContent=authMode==="signup"?"Create account":"Sign in"}
$("#authBtn").onclick=()=>openAuth("login");$$(".auth-tab").forEach(b=>b.onclick=()=>{authMode=b.dataset.auth;renderAuth()});
$$("[data-close]").forEach(b=>b.onclick=()=>$("#"+b.dataset.close).classList.remove("open"));
$("#authForm").onsubmit=async e=>{e.preventDefault();let fd=new FormData(e.target),data=Object.fromEntries(fd.entries());let res=await api(authMode==="signup"?"signup":"login",data);if(!res.ok){toast(res.error||"Unable to sign in");return}currentUser=res.user;$("#authModal").classList.remove("open");toast(authMode==="signup"?"Account created! Welcome 🎉":"Welcome back, "+currentUser.name+" 👋");syncUI();renderAnalytics();renderNotifications();};
async function checkSession(){let res=await api("me");if(res.ok&&res.user)currentUser=res.user;syncUI();renderAnalytics()}checkSession();

function renderNotifications(){let ns=state.notifications||[];$("#notificationList").innerHTML=ns.map(n=>`<div class="notification"><b>${escapeHTML(n.title)}</b><div>${escapeHTML(n.body)}</div><small>${escapeHTML(n.time)}</small></div>`).join("");$("#notifCount").textContent=ns.length||""}
$("#notifications").onclick=e=>{$("#notifPanel").classList.toggle("open");e.stopPropagation()};document.addEventListener("click",e=>{if(!e.target.closest(".actions"))$("#notifPanel").classList.remove("open")});$("#markRead").onclick=()=>{state.notifications=[];saveState();renderNotifications();toast("Notifications cleared")};renderNotifications();

let qSeed=[...CURRICULUM.flatMap(s=>s.chapters.flatMap(c=>c.topics.map(t=>({subject:s.subject,chapter:c.name,topic:t.name,question:`Which statement best describes ${t.name}?`,options:[t.definition,"It is unrelated to this subject.","It is only a historical term.","It has no practical meaning."],answer:0}))))];
function startQuiz(){let subject=$("#quizSubject").value,count=+$("#quizCount").value;let pool=qSeed.filter(q=>subject==="All Subjects"||q.subject===subject).sort(()=>Math.random()-.5);quiz=pool.slice(0,count);qIndex=0;qScore=0;renderQuestion()}
function renderQuestion(){if(!quiz.length){$("#quiz").innerHTML='<div class="card"><h2>No questions found.</h2></div>';return}if(qIndex>=quiz.length){let acc=Math.round(qScore/quiz.length*100);state.solved+=quiz.length;state.correct+=qScore;saveState();if(currentUser){api("progress",{solved:quiz.length,correct:qScore,studyMinutes:5}).then(r=>{if(r.ok){currentUser=r.user;syncUI();renderAnalytics()}})}else syncUI();$("#quiz").innerHTML=`<div class="quiz-card" style="text-align:center"><div style="font-size:48px">🏆</div><h2>Test complete</h2><p>You scored <b>${qScore}/${quiz.length}</b> — ${acc}% accuracy.</p><button class="primary" id="again">New randomized set →</button>${!currentUser?'<p class="muted">Sign in to save this performance to your profile.</p>':''}</div>`;$("#again").onclick=startQuiz;return}let q=quiz[qIndex];$("#quiz").innerHTML=`<div class="quiz-card"><div class="qmeta"><span>Question ${qIndex+1}/${quiz.length}</span><span>${escapeHTML(q.subject)} • ${escapeHTML(q.chapter)}</span></div><h2>${escapeHTML(q.question)}</h2><div class="options">${q.options.map((o,i)=>`<button class="option" data-i="${i}">${String.fromCharCode(65+i)}. ${escapeHTML(o)}</button>`).join("")}</div></div>`;$$(".option").forEach(b=>b.onclick=()=>{let i=+b.dataset.i;$$(".option").forEach(x=>x.disabled=true);if(i===q.answer){b.classList.add("correct");qScore++;toast("Correct ✓")}else{b.classList.add("wrong");$$(".option")[q.answer].classList.add("correct");toast("Review this definition")}setTimeout(()=>{qIndex++;renderQuestion()},500)})}
$("#startQuiz").onclick=startQuiz;

function renderNotes(){let ns=currentUser?.notes||state.notes||[];$("#notesGrid").innerHTML=ns.length?ns.map((n,i)=>`<article class="note-card"><h3>${escapeHTML(n.title)}</h3><p>${escapeHTML(n.body)}</p><small class="muted">${escapeHTML(n.date||"Saved")}</small></article>`).join(""):'<div class="card"><h2>No notes yet</h2><p class="muted">Create your first note above.</p></div>'}
$("#saveNote").onclick=async()=>{let title=$("#noteTitle").value.trim(),body=$("#noteBody").value.trim();if(!title||!body)return toast("Add title and note.");let n={title,body,date:new Date().toLocaleDateString()};if(currentUser){let r=await api("note",{title,body});if(r.ok)currentUser.notes=r.user.notes;else return toast(r.error)}else{state.notes.unshift(n);saveState()}$("#noteTitle").value="";$("#noteBody").value="";renderNotes();toast("Note saved ✓")};renderNotes();

function addChat(text,who){$("#chat").insertAdjacentHTML("beforeend",`<div class="msg ${who}">${escapeHTML(text)}</div>`);$("#chat").scrollTop=99999}
addChat("Hi Ankush! I can help you navigate the study material. For a real AI answer, connect your preferred AI API on the server.", "bot");
$("#aiSend").onclick=()=>{let x=$("#aiInput").value.trim();if(!x)return;addChat(x,"user");$("#aiInput").value="";setTimeout(()=>addChat("Study tip: use the chapter page to read the definition and notes, then practice questions and revisit the topic during revision.","bot"),250)};
$("#aiInput").addEventListener("keydown",e=>{if(e.key==="Enter")$("#aiSend").click()});$$("[data-prompt]").forEach(b=>b.onclick=()=>{$("#aiInput").value=b.dataset.prompt;$("#aiSend").click()});

function drawTimer(){let m=Math.floor(timer/60),s=timer%60;$("#timer").textContent=`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`}
$("#timerStart").onclick=()=>{if(timerInt)return;timerInt=setInterval(()=>{timer--;drawTimer();if(timer<=0){clearInterval(timerInt);timerInt=null;timer=1500;drawTimer();toast("Focus session complete 🎉");if(currentUser)api("study",{minutes:25}).then(r=>{if(r.ok){currentUser=r.user;syncUI();renderAnalytics()}})}},1000);toast("Focus session started")};
$("#timerReset").onclick=()=>{clearInterval(timerInt);timerInt=null;timer=1500;drawTimer()};drawTimer();

$("#feedbackOpen").onclick=()=>$("#feedbackModal").classList.add("open");
$("#feedbackForm").onsubmit=async e=>{e.preventDefault();let data={name:$("#fbName").value,email:$("#fbEmail").value,type:$("#fbType").value,message:$("#fbMessage").value};let r=await api("feedback",data);if(!r.ok)return toast(r.error||"Feedback could not be sent");$("#feedbackModal").classList.remove("open");e.target.reset();toast("Thank you! Feedback sent ✓")};

$("#librarySearch").oninput=renderLibrary;$("#subjectSelect").onchange=renderLibrary;$("#search").onkeydown=e=>{if(e.key==="Enter"){let v=e.target.value.trim();$("#librarySearch").value=v;page("library");renderLibrary()}};
populateSelects();renderLibrary();renderEntrance("cee",["Physics","Chemistry","Biology","English"]);renderEntrance("ioe",["Mathematics","Physics","Chemistry","English","Computer"]);syncUI();
setTimeout(()=>$("#loader").classList.add("loader-hidden"),550);
